### PR TITLE
Support landscape mode.

### PR DESCRIPTION
**Pull request by josephyu1110**
- #1231

### CODE REVIEW

**Comment by josephyu1110** [comment]
Using onWindowFocusChanged() in BrowserFragment to determine when to update screen orientation may not work on:
- HomeFragment is displayed
- UrlInputFragment is displayed
- FindInPage is displayed

**Comment by josephyu1110** [comment]
After investigation, using a landscape BrowserFragment still need to create it in many places as current implementation does. See [comparison](https://docs.google.com/spreadsheets/d/1YtHdsKH3BAg9tiXFeLOeNbQ2JicXG0N-IWyj4a5kU_Y/edit#gid=433832423).

**Comment by josephyu1110** [comment]
TBD: Need to add telemetry for private browsing as well?

**Comment by cnevinc** [comment]
Per discussion with @Jacklin-ux 
We only need to care about orientation change when the user is currently looking at BrowserFragment.
This PR here also want to take care about Landscape Home-> Landscape BrowserFragment scenario. 
Maybe this could be easier.

I don't have time to review this since I'm working on Content Portal

Per discussion with @josephyu1110 , it's better if we can keep the state in another FullScreenBrowserFragment and reduce the reponsility of BrowserFragment. This need another sprint of implemtation.

**Pull request closed without merging**
